apiVersion: batch/v1
kind: CronJob
metadata:
  name: time-limited-job2
spec:

  jobTemplate:
    metadata:
      name: time-limited-job2
    spec:
      activeDeadlineSeconds: 12 
      template:
        metadata: {}
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            name: time-limited-job2
            resources: {}
          restartPolicy: Never
  schedule: '* * * * *'
status: {}