apiVersion: batch/v1
kind: CronJob
metadata:
  name: time-limited-job
spec:
  time-limited-job.yaml: 17
  jobTemplate:
    metadata:
      name: time-limited-job
    spec:
      template:
        metadata: {}
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            name: time-limited-job
            resources: {}
          restartPolicy: Never
  schedule: '* * * *'
status: {}